### ISSUE TITLE
Attach debugging information to instructions in LLVM IR

### ISSUE THREAD

**Issue by lung21** [sbip-sg/tsll#6]
#### Motivation

This new feature is to provide metadata information about mapping source code to LLVM IR for debuggers and analyzers to consume. They use the information to detect necessary bugs and improve the code quality if any.

#### References
https://llvm.org/docs/SourceLevelDebugging.html#id4

**Comment by lung21** [comment]
@taquangtrung 
The original LLVM bindings does not support for `DIBuilder` and other necessary functionality of attaching debug metadata. We'll have to extend the implementation on our own.

The current support including the functionality extended previously, is curated in https://github.com/sbip-sg/llvm-node/blob/master/llvm-node.d.ts

**Comment by taquangtrung** [comment]
Thanks @lung21! It looks like we'll have to implement that feature. 

Here is the similar bindings built for OCaml: https://reviews.llvm.org/rG506df1bbfd16233134a6ddea96ed2d49077840fd
(There is a lot of code written for these OCaml bindings)

Can you investigate if we can develop similar bindings for Typescript?

**Comment by lung21** [comment]
@taquangtrung No problem 👍🏼 
Since I have the previous experience implementing more bindings to https://github.com/sbip-sg/llvm-node, the debug-related support can be added as well. But only the functionality we need will be developed on a rolling basis for now.

**Comment by lung21** [comment]
Implemented, under test
